server.port=10346

spring.application.name=book-api
spring.profiles.active=dev

eureka.client.service-url.defaultZone=http://localhost:10344/eureka,http://localhost:10345/eureka

# Config Server \uC124\uC815\uC744 \uAC00\uC838\uC634 (Eureka \uC5F0\uB3D9 \uC2DC \uC8FC\uC18C \uC0DD\uB7B5)
spring.config.import=optional:configserver:

# Eureka \uB4F1 \uC11C\uBE44\uC2A4 \uB514\uC2A4\uCEE4\uBC84\uB9AC\uB85C Config Server \uC704\uCE58 \uD0D0\uC0C9 \uD65C\uC131\uD654
spring.cloud.config.discovery.enabled=true

# Eureka\uC5D0 \uB4F1\uB85D\uB41C Config Server\uC758 \uC11C\uBE44\uC2A4 \uC774\uB984
spring.cloud.config.discovery.service-id=config-server

# \uAC00\uC838\uC62C \uC124\uC815 \uD30C\uC77C \uC774\uB984(naver-api.yml \uB4F1)
spring.cloud.config.name=naver-api,mysql,elasticsearch,minio

spring.elasticsearch.uris=http://10.116.64.14:9200

# DBCP2 \uC801\uC6A9
spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource

spring.datasource.dbcp2.initial-size=200
spring.datasource.dbcp2.max-total=200
spring.datasource.dbcp2.max-idle=200
spring.datasource.dbcp2.min-idle=200
spring.datasource.dbcp2.validation-query=SELECT 1
spring.datasource.dbcp2.test-on-borrow=true

management.endpoints.web.exposure.include=health, info

# jpa \uC11C\uBC84 \uC2DC\uAC04 \uC124\uC815
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

minio.bucket.name=beansolid-book-image